# Generated by Django 5.2.1 on 2025-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
