# Generated by Django 5.2 on 2025-05-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('grade', models.IntegerField()),
                ('major', models.CharField(max_length=50)),
            ],
        ),
    ]
