# Generated by Django 5.2 on 2025-05-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hacsam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('stdnum', models.IntegerField()),
                ('major', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
